#!/bin/bash

msg() {
    local prefix
    local message
    local redirect

    case $1 in
        -e|--error)
            prefix="${RED}ERROR${NC}  "
            message="$2"
            redirect=">&2"

            shift 2
            ;;
        -i|--info)A
            prefix="${GREEN}INFO${NC}   "
            message="$2"

            shift 2
            ;;
        *)
            message="$1"

            shift
            ;;
    esac
    
    local tail="$@"
    [ -z "$tail" ] && echo -e "${prefix}${message}" $redirect || msg $tail
}

secure_curl() {
    local URL="$1"
    
    if ! curl --proto '=https' -sSf "$URL"; then
        msg -e "Failed to transfer data from ${YELLOW}$URL${NC}"
        return 1
    fi
}

eval_curl() {
    local URL="$1"

    local data="$(secure_curl "$URL")"
    if ! eval "$data"; then
        msg -e "Failed to evaluate data from ${YELLOW}$URL${NC}"
        return 1
    fi
}

ROOT_URL="https://raw.githubusercontent.com/skeletony007/charon/main"
BASH_UTILS_URL="https://raw.githubusercontent.com/skeletony007/bash-utils/main"

eval_curl "$ROOT_URL/colors"
eval_curl "$BASH_UTILS_URL/object/object"

abstract_ferry="$(secure_curl "$ROOT_URL/punts/abstract-ferry")"


action=$1

case $action in
    install|uninstall|config)
        shift
        for ferry in "$@"; do
            ferry_data="$(secure_curl "$ROOT_URL/ferries/$ferry")"

            create_object $ferry "$abstract_ferry"
            create_object $ferry "$ferry_data"

            ${ferry}_${action}

            case $? in
                0)
                    msg -i "$action succeeded"
                    ;;
                *)
                    msg -e "$action unsuccessful"
                    ;;
            esac
        done
    ;;
    --help|-h)
        secure_curl "$ROOT_URL/usage"
    ;;
    *)
        msg -e "Invalid command or missing arguments. Use ${YELLOW}charon --help${NC} for usage instructions."
    ;;
esac

