#!/bin/bash

BASH_UTILS_URL="https://raw.githubusercontent.com/skeletony007/bash-utils/main"
REMOTE_FILE="https://raw.githubusercontent.com/skeletony007/charon/main/stream"
LOCAL_DIR="$HOME/bin"
LOCAL_FILE="$LOCAL_DIR/charon"

eval "$(
    curl --proto '=https' -sSf "$BASH_UTILS_URL/shell-functions/shell-functions"
)"

mkdir -p "$LOCAL_DIR" && \
curl --proto '=https' -sSfL -o "$LOCAL_FILE" "$REMOTE_FILE" && \
chmod +x "$LOCAL_FILE" && \
add_to_path "$LOCAL_DIR"

