#!/bin/bash

BASH_UTILS_URL="https://raw.githubusercontent.com/skeletony007/bash-utils/main"
LOCAL_DIR="$HOME/bin"
LOCAL_FILE="$LOCAL_DIR/charon"

eval "$(
    curl --proto '=https' -sSf "$BASH_UTILS_URL/shell-functions/shell-functions"
)"

rm "$LOCAL_FILE" && \
[ -z "$(ls -A "$LOCAL_DIR")" ] && \
rm -rf "$LOCAL_DIR" && \
remove_from_path "$LOCAL_DIR"

