#!/bin/bash

${obj}_install() {
    msg "Not implemented: This method would install ${obj}"
    return 1
}

${obj}_uninstall() {
    msg "Not implemented: This method would uninstall ${obj}" 
    return 1
}

${obj}_config() {
    msg "Not implemented: This method would configure ${obj}"
    return 1
}

