#!/bin/bash

${obj}_init() {
    create_object ${obj} "$GH_WRAPPER_DATA"

    ${obj}_user="$1"
    ${obj}_repo="$2"
    ${obj}_branch="$3"; [[ -z ${${obj}_branch} ]] && ${obj}_branch=main
}

${obj}__fill_url() {
    local url_pattern="$1"

    local user="${${obj}_user}"
    local repo="${${obj}_repo}"

    echo "$(printf "$url_pattern" "${${obj}_user}" "${${obj}_repo}")"
}

${obj}_download() {
    local path=$1 ## `path` could be just: `""` for the _root_
    local output=$2

    local branch="${${obj}_branch}"

    local url="$(
        ${obj}__fill_url "$(dirname "https://api.github.com/repos/%s/%s/contents/$path")""?ref=$branch"
    )"
    local path_type

    if [[ -z $path ]]; then
        path_type=dir
    else
        local regex='"path":[ ]*"'"${path//./\\.}"'"[^}]*"type":[ ]*"([^"]*)"'
        path_type=$(${obj}_get_api_data "$url" "$regex")
    fi

    echo "$url"
    echo "$path_type"
    echo "Downloading $path -> $output"

    case $path_type in
        file)
            local download_url="$(
                ${obj}__fill_url "https://raw.githubusercontent.com/%s/%s/main/$path"
            )"
            curl --proto '=https' -# -o "$output" "$download_url"
            ;;
        dir)
            mkdir "$output"

            local url="$(
                ${obj}__fill_url "https://api.github.com/repos/%s/%s/contents/$path?ref=$branch"
            )"
            local path
            local paths_regex='"path":[ ]*"([^"]*)"'
            local paths="$(${obj}_get_api_data "$url" "$paths_regex")"
            for path in $paths; do
                ${obj}_download "$path" "$output/$(basename "$path")"
            done
            ;;
    esac
}

${obj}_get_release_download_urls() {
    if [[ -z ${${obj}_release_download_urls} ]]; then
        local url="$(
            ${obj}__fill_url 'https://api.github.com/repos/%s/%s/releases/latest'
        )"

        local regex='"browser_download_url":[ ]*"([^"]*)"'

        ${obj}_release_download_urls="$(
            ${obj}_get_api_data "$url" "$regex"
        )"
    fi

    echo "${${obj}_release_download_urls}"
}

${obj}_get_release_asset_names() {
    [[ -z "${${obj}_release_asset_names}" ]] && ${obj}_release_asset_names="$(
        basename "$(${obj}_get_release_download_urls)"
    )"

    echo "${${obj}_release_asset_names}"
}

${obj}_get_remote_version() {
    if [[ -z "${${obj}_remote_version}" ]]; then
        local url="$(
            ${obj}__fill_url 'https://api.github.com/repos/%s/%s/releases/latest'
        )"

        local regex='"tag_name":[ ]*"([^"]*)"'

        ${obj}_remote_version="$(
            ${obj}_get_api_data "$url" "$regex"
        )"
    fi

    echo "${${obj}_remote_version}"
}

${obj}_get_local_version() {
    msg -w "Not implemented: Returns the local version of the program"
}

${obj}_is_latest() {
    local remote_version="$(${obj}_get_remote_version)"
    local local_version="$(${obj}_get_local_version)"

    [ "$local_version" == "$remote_version" ] || return 1
}

${obj}_release_download_asset() {
    local asset_name="$1"
    local output="$2"

    local url="$(
        ${obj}__fill_url "https://github.com/%s/%s/releases/latest/download/$asset_name"
    )"

    curl --proto '=https' -# -L -o "$output" "$url"
}

${obj}_release_menu() {
    local os_name
    case "$(uname -s)" in
        "Darwin")
            os_name="macos"
            ;;
        "Linux")
            os_name="linux"
            ;;
        *)
            echo "Unsupported operating system"
            return 1
            ;;
    esac
    local arch_name="$(uname -m)"

    echo "Detected operating system: $os_name \nDetected architecture: $arch_name"

    local asset_names="$(${obj}_get_release_asset_names)"

    local asset_names_with_arch_and_os="$(
        echo "$asset_names" | grep -Ei "$os_name.*$arch_name|$arch_name.*$os_name"
    )"
    local asset_names_with_arch_or_os="$(
        echo "$asset_names" | grep -Ei "$os_name|$arch_name"
    )"

    if [[ ! "$asset_names_with_arch_and_os" == "" ]]; then
        asset_names="$asset_names_with_arch_and_os"
    elif [[ ! "$asset_names_with_arch_or_os" == "" ]]; then
        asset_names="$asset_names_with_arch_or_os"
    fi

    local selected_asset
    PS3="Select the asset to download: "
    select asset in $asset_names; do
        if [[ -n "$asset" ]]; then
            selected_asset="$asset"
            break
        else
            echo "Invalid selection, please choose a valid asset."
        fi
    done

    echo "$selected_asset"
}

