#!/bin/bash

${obj}_init()
{
    ${obj}_token="$(<"$HOME/.gh-wrapper/token")"
}

${obj}_get_api_data()
{
    local url="$1"
    local regex="$2"

    local data

    [ -z ${${obj}_token} ] || local auth="Authorization: Bearer ${${obj}_token}"
    local version="2022-11-28"

    local response="$(
        curl -s \
             --request GET \
             --url "$url" \
             --header "$auth" \
             --header "X-GitHub-Api-Version: $version" \
    )"

    if [[ $response =~ $regex ]]
    then
        data="$BASH_REMATCH"
    fi

    echo "$data"
}

