#!/bin/bash

${obj}_init() {
    ${obj}_token="$(<"$HOME/.gh-wrapper/token")"
}

${obj}_get_api_data() {
    local value="$1"
    local URL="$2"

    [ -z ${${obj}_token} ] || local auth="Authorization: Bearer ${${obj}_token}"
    local version="2022-11-28"

    local temp_data="$( \
        curl -s \
             --request GET \
             --url "$URL" \
             --header "$auth" \
             --header "X-GitHub-Api-Version: $version" \
        | grep -oE "\"$value\": \"[^\"]*" \
    )"
    local processed_data="$(echo "$temp_data" | sed "s/\"$value\": \"//")"

    echo "$processed_data"
}

