#!/bin/bash

${obj}_install() {
    echo "This method would install the program"
    exit 1
}

${obj}_uninstall() {
    echo "This method would uninstall the program"
    exit 1
}

${obj}_config() {
    echo "This method would configure the program"
    exit 1
}

