#!/bin/bash

${obj}_install() {
    report -i "This method would install the program"
    exit 1
}

${obj}_uninstall() {
    report -i "This method would uninstall the program" 
    exit 1
}

${obj}_config() {
    report -i "This method would configure the program"
    exit 1
}

