#!/bin/bash

regex() {
    local regex=$1
    local string=$2

    if [[ $string =~ $regex ]]; then
        echo ${BASH_REMATCH[@]:1}
        regex "$regex" "${string#*${BASH_REMATCH[0]}*}"
    fi
}

