#!/bin/bash

${obj}_init() {
    create_object ${obj}_dotfiles "$GH_REPO_DATA" skeletony007 .dotfiles
    create_object ${obj} "$GH_REPO_DATA" alacritty alacritty
    create_object ${obj} "$CLI_PROGRAM_DATA" alacritty

    create_object ${obj}_catppuccin "$GH_REPO_DATA" catppuccin alacritty

    case "$(uname -s)" in
        "Darwin")
            ${obj}_APPLICATION_DIR='/Applications/Utilities/Alacritty.app'
            ;;
    esac
}

${obj}_install() {
    if ${obj}_is_latest; then
        msg --not-upgrading ${obj}
    else
        msg --installing ${obj}
        # Just install the Alacritty binary.
        #
        # See https://github.com/alacritty/alacritty/blob/master/INSTALL.md
        #
        cargo install alacritty

    fi
    case "$(uname -s)" in
        "Darwin")
            local APPLICATION_DIR="${${obj}_APPLICATION_DIR}"
            mkdir -p "$APPLICATION_DIR"

            # Configure the Alacritty.app for macOS.
            #
            # Uses the same icon as Terminal.app
            #$(declare -p)
            sudo eval "
                ${obj}_dotfiles_download '.alacritty/Alacritty.app' \"$APPLICATION_DIR\"
            "
            sudo mkdir -p "$APPLICATION_DIR/Contents/MacOS"
            sudo ln -s "$HOME/.cargo/bin/alacritty" \
                       "$APPLICATION_DIR/Contents/MacOS/alacritty"
            sudo mkdir -p "$APPLICATION_DIR/Contents/Resources"
            sudo ln -s '/System/Applications/Utilities/Terminal.app/Contents/Resources/Terminal.icns' \
                       "$APPLICATION_DIR/Contents/Resources/alacritty.icns"
            ;;
    esac

    # Download catppuccin themes.
    #
    # See https://github.com/catppuccin/alacritty#usage
    #
    msg --installing catppuccin-frappe
    mkdir -p "$HOME/.config/alacritty/catppuccin"
    ${obj}_catppuccin_download 'catppuccin-frappe.yml' "$HOME/.config/alacritty/catppuccin/catppuccin-frappe.yml"

    msg 'Adding alacritty.yml from dotfiles'
    mkdir -p "$HOME/.config/alacritty/"
    ${obj}_dotfiles_download '.alacritty/alacritty.yml' "$HOME/.config/alacritty/alacritty.yml"
}

${obj}_uninstall() {
    cargo uninstall alacritty

    msg --uninstalling "$BIN_DIR/camilladsp"
    case "$(uname -s)" in
        "Darwin")
            local APPLICATION_DIR="${${obj}_APPLICATION_DIR}"

            # Remove the Alacritty.app Utility for macOS.
            #
            msg --uninstalling "$APPLICATION_DIR"
            sudo rm -rf "$APPLICATION_DIR"
            ;;
    esac
    
    rm -rf "$HOME/.config/alacritty/catppuccin" \
           "$HOME/.config/alacritty/alacritty.yml"
}

