#!/bin/bash

${obj}_init() {
    create_object ${obj} "$gh_releases_data" "HEnquist" "camilladsp"
    create_object ${obj} "$cli_program_data" camilladsp

    ${obj}_BIN_DIR="$HOME/.camilladsp/bin"

    declare -A ${obj}_preferences
    case "$(uname -s)" in
        "Darwin")
            ${obj}_preferences[asset]="camilladsp-macos-aarch64.tar.gz"
            ;;
        *)
            msg -e "Unsupported operating system."; return 1
            ;;
    esac
}

${obj}_install() {
    local BIN_DIR="${${obj}_BIN_DIR}"
    local PATH="$BIN_DIR:$PATH"

    if ${obj}_is_latest; then
        msg "Already up to date."
    else
        mkdir -p "$BIN_DIR" 
        ${obj}_download_asset "${${obj}_preferences[asset]}" - \
        | tar -zxvf - -C "$BIN_DIR"
        [ $? -eq 0 ] || return 1
    fi
    
    add_to_path "$BIN_DIR"
}

${obj}_uninstall() {
    local BIN_DIR="${${obj}_BIN_DIR}"

    rm "$BIN_DIR/camilladsp"
    remove_from_path "$BIN_DIR"
}

