#!/bin/bash

${obj}_init() {
    create_object ${obj} "$gh_wrapper_data" "HEnquist" "camilladsp"
    create_object ${obj} "$cli_program_data" camilladsp

    ${obj}_BIN_DIR="$HOME/.camilladsp/bin"

    case "$(uname -s)" in
        "Darwin")
            local release="camilladsp-macos-aarch64.tar.gz"
            ;;
        *)
            msg -e "Unsupported operating system."; return 1
            ;;
    esac
}

${obj}_install() {
    local BIN_DIR="${${obj}_BIN_DIR}"

    mkdir -p "$BIN_DIR" && local PATH="$BIN_DIR:$PATH"

    if ${obj}_is_latest; then
        msg "Already up to date."
    else
        ${obj}_download_asset "$release" - | tar -zxvf - -C "$BIN_DIR"
        [ $? -eq 0 ] || return 1
    fi

    add_to_path "$BIN_DIR"
}

${obj}_uninstall() {
    local BIN_DIR="${${obj}_BIN_DIR}"

    rm "$BIN_DIR/camilladsp"
    remove_from_path "$BIN_DIR"
}

