#!/bin/bash

${obj}_init() {
    create_object ${obj} "$GH_REPO_DATA" "skeletony007" ".dotfiles"

    ${obj}_TEST_DIR="$HOME/${obj}"
}

${obj}_install() {
    local test_dir="${${obj}_TEST_DIR}"
    
    ${obj}_download_dir '.firefox' "$test_dir/.firefox"
}

