#!/bin/bash

${obj}_init() {
    create_object ${obj} "$GH_REPO_DATA" "skeletony007" "charon"

    ${obj}_TEST_DIR="$HOME/${obj}"
}

${obj}_install() {
    local test_dir="${${obj}_TEST_DIR}"
    
    ${obj}_download_dir 'punts' "$test_dir/punts"
}

