#!/bin/bash

${obj}_install() {
    msg --installing tunnelblick

    asset_url="https://tunnelblick.net/iprelease/Latest_Tunnelblick_Stable.dmg"
    package="Tunnelblick.app"

    msg --downloading "Latest_Tunnelblick_Stable.dmg"

    TMP_FILE=$(mktemp)
    curl --proto '=https' -# -L -o "$TMP_FILE" "$asset_url"
    sudo hdiutil attach "$TMP_FILE"
    sudo cp -r "/Volumes/Tunnelblick/$package" "/Applications"
    sudo hdiutil detach "/Volumes/Tunnelblick"
    rm "$TMP_FILE"

    sudo chown -R root "/Applications/$package"
}

